### PR TITLE
Fix issue when disconnection occurs before WS handshake

### LINKED ISSUE #149: Crash on getMessageHandler()
Using v2.2, Websocket crashes when I call the URI to my websocket. I've set up SSL to use WSS.

First few lines of the error stack:
`
Type error: Argument 1 passed to Nekland\Woketo\Server\WebSocketServer::getMessageHandler() must be of the type string, null given, called in /mnt/c/Users/HTECH-Shaun/projects/shareapi/vendor/nekland/woketo/src/Server/WebSocketServer.php on line 162 in /mnt/c/Users/HTECH-Shaun/projects/shareapi/vendor/nekland/woketo/src/Server/WebSocketServer.php:208
Stack trace:
#0 /mnt/c/Users/HTECH-Shaun/projects/shareapi/vendor/nekland/woketo/src/Server/WebSocketServer.php(162): Nekland\Woketo\Server\WebSocketServer->getMessageHandler(NULL, Object(Nekland\Woketo\Server\Connection))
#1 /mnt/c/Users/HTECH-Shaun/projects/shareapi/vendor/nekland/woketo/src/Core/AbstractConnection.php(147): Nekland\Woketo\Server\WebSocketServer->Nekland\Woketo\Server\{closure}(NULL, Object(Nekland\Woketo\Server\Connection))
`

This is my instance:

```
private $connConfig = [
        'ssl' => true,
        'certFile' => '/etc/apache2/ssl/apache.pem',
        'sslContextOptions' => [
            'verify_peer' => false,
            'allow_self_signed' => true
        ]
 ];

$server = new WebSocketServer(8080, '127.0.2.1', $this->connConfig);
$server->setMessageHandler(new WebsocketWoketo(), '/ivm');
$server->start();
```

### PR DESCRIPTION
**Pull request by Nek-**
When you disconnect from woketo and the handshake is not done, then
woketo can't know what WS handler to call leading to an error. In
this commit I disable handler retrieval if the handshake is not done.

This also adds a little log message.

Fix #149 

It also fixes an old test that was not doing things as expected.

### CODE REVIEW

File: src/Core/AbstractConnection.php [hunk 1]
```diff
@@ -83,6 +84,7 @@ public function __construct(MessageProcessor $messageProcessor, LoopInterface $l
         $this->handshake = $handshake;
         $this->messageProcessor = $messageProcessor;
         $this->loop = $loop;
+        $this->logger = new NullLogger();
```
Comment (Shine-neko) [inline src/Core/AbstractConnection.php]: heu ?

File: src/Core/AbstractConnection.php [hunk 2]
```diff
@@ -140,7 +142,7 @@ public function getLogger()
      */
     protected function getHandler() : MessageHandlerInterface
     {
-        if ($this->handler instanceof \Closure) {
+        if (!$this->handler instanceof MessageHandlerInterface) {
```
Comment (Shine-neko) [inline src/Core/AbstractConnection.php]: BC break ?

File: src/Core/AbstractConnection.php (hunk 1 above)
Comment (mcsky) [reply src/Core/AbstractConnection.php]: wut ?

Comment (Nek-) [reply src/Core/AbstractConnection.php]: I really think an attribute named "logger" should never contain "null" but "NullLogger". There are many similar other points that may be improved in that class. But well, here is one.

File: src/Core/AbstractConnection.php (hunk 2 above)
Comment (Nek-) [reply src/Core/AbstractConnection.php]: No, it now allows callable as handler value. I just inversed the condition here. (you probably miss the `!`)
