### PR TITLE
Fix wstest 3.7

### LINKED ISSUE #41: Solve wstest 3.7
See #1

### PR DESCRIPTION
**Pull request by Nek-**
Now the close message handler can detect wrong close frames.

Fixes #41 

Non regression proof:

image
image
image

it also fixes 5.1 & 5.2

### CODE REVIEW

File: src/Rfc6455/MessageHandler/CloseFrameHandler.php [hunk 1]
```diff
@@ -24,7 +24,15 @@ public function supports(Message $message)
 
     public function process(Message $message, MessageProcessor $messageProcessor, ConnectionInterface $socket)
     {
-        $messageProcessor->write($messageProcessor->getFrameFactory()->createCloseFrame(), $socket);
+        $code = Frame::CLOSE_NORMAL;
+
+        foreach ($message->getFrames() as $frame) {
+            if ($frame->getRsv1() || $frame->getRsv2() || $frame->getRsv3()) {
+                $code = Frame::CLOSE_PROTOCOL_ERROR;
```
Comment (folliked) [inline src/Rfc6455/MessageHandler/CloseFrameHandler.php]: why not a break ?
