### PR TITLE
Fix wstest 4.1.1 & 4.4.2 by adding wrong opcode handler

### LINKED ISSUE #24: Solve wstest 4.1.1
See #1

### PR DESCRIPTION
**Pull request by Nek-**
image
image

This fixes #24

### CODE REVIEW

File: src/Rfc6455/MessageHandler/WrongOpcodeHandler.php [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+use Nekland\Woketo\Rfc6455\Frame;
+use Nekland\Woketo\Rfc6455\Message;
+use Nekland\Woketo\Rfc6455\MessageProcessor;
+use React\Socket\ConnectionInterface;
+
+class WrongOpcodeHandler implements Rfc6455MessageHandlerInterface
+{
+    public function supports(Message $message)
+    {
+        return in_array($message->getOpcode(), [3, 4, 5, 6, 7, 10, 11, 12, 13, 14, 15]);
```
Comment (folliked) [inline src/Rfc6455/MessageHandler/WrongOpcodeHandler.php]: explain that it is the opcode reserved  for the future and they are considered wrong opcode for now only ? no ?
